apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-api
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: {{ .Values.service.api.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-api