apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mail-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-mail
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.mail.port }}
      targetPort: {{ .Values.service.mail.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-mail
